import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "sw" | "hi" | "tr" | "zh";

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    about: "About",
    services: "Services",
    projects: "Projects",
    contact: "Contact",
    professionalExperience: "Professional Experience",
    tagline: "Building Landscapes, Shaping Futures",
    subtitle: "GreenScape Consults Tz Ltd",
    ourServices: "OUR SERVICES",
    viewProjects: "VIEW PROJECTS",
    projectsCompleted: "Projects",
    yearsExperience: "Years",
    happyClients: "Clients",
    aboutUs: "About Us",
    whereArchMeetsNature: "Where Architecture Meets Nature",
    aboutDesc1: "Founded in Tanzania, Greenscape Consults Tz is a dynamic and integrated firm specializing in the seamless confluence of built structures and natural environments.",
    aboutDesc2: "Our \"whole-environment\" approach ensures that every project is conceived, designed, and constructed with a unified vision.",
    ourVision: "Our Vision",
    visionDesc: "To be Tanzania's leading integrated design and build partner, creating sustainable and inspiring spaces where architecture and nature thrive in harmony.",
    ourMission: "Our Mission",
    missionDesc: "We deliver exceptional, holistic design and construction solutions for buildings and landscapes.",
    whatWeDo: "What We Do",
    ourServicesTitle: "Our Services",
    viewCategories: "View Categories",
    portfolio: "Portfolio",
    featuredProjects: "Featured Projects",
    viewProcess: "View Process",
    contactUs: "Contact Us",
    quickLinks: "Quick Links",
    getInTouch: "Get In Touch",
    getInTouchDesc: "Have a project? Get in touch. There's no obligation.",
    testimonials: "Testimonials",
    whatClientsSay: "What Our Clients Say",
    allRightsReserved: "All rights reserved.",
    landscapePlanning: "Landscape Planning & Design",
    landscapePlanningDesc: "Comprehensive site analysis, master planning, and creative garden design with sustainable solutions.",
    architecturalBuildings: "Architectural Buildings & Constructions",
    architecturalBuildingsDesc: "Full architectural design, building construction, and structural engineering services.",
    projectManagement: "Project Management & Constructions",
    projectManagementDesc: "End-to-end construction supervision and project management ensuring quality delivery.",
    close: "Close",
    categories: "Categories",
    professionalExperienceDesc: "Our team brings over a decade of hands-on experience in landscape architecture, building design, and project management across Tanzania and East Africa.",
  },
  sw: {
    home: "Nyumbani",
    about: "Kuhusu",
    services: "Huduma",
    projects: "Miradi",
    contact: "Wasiliana",
    professionalExperience: "Uzoefu wa Kitaalamu",
    tagline: "Kujenga Mandhari, Kuunda Mustakabali",
    subtitle: "GreenScape Consults Tz Ltd",
    ourServices: "HUDUMA ZETU",
    viewProjects: "ANGALIA MIRADI",
    projectsCompleted: "Miradi",
    yearsExperience: "Miaka",
    happyClients: "Wateja",
    aboutUs: "Kuhusu Sisi",
    whereArchMeetsNature: "Ambapo Usanifu Unakutana na Asili",
    aboutDesc1: "Ikianzishwa Tanzania, Greenscape Consults Tz ni kampuni yenye nguvu inayobobea katika muunganiko wa majengo na mazingira ya asili.",
    aboutDesc2: "Mbinu yetu ya \"mazingira yote\" inahakikisha kila mradi unabuniwa na kujengwa kwa maono ya pamoja.",
    ourVision: "Maono Yetu",
    visionDesc: "Kuwa mshirika mkuu wa Tanzania katika kubuni na kujenga, kuunda nafasi endelevu na za kuvutia.",
    ourMission: "Dhamira Yetu",
    missionDesc: "Tunatoa suluhisho bora za kubuni na ujenzi kwa majengo na mandhari.",
    whatWeDo: "Tunachofanya",
    ourServicesTitle: "Huduma Zetu",
    viewCategories: "Angalia Aina",
    portfolio: "Kazi Zetu",
    featuredProjects: "Miradi Iliyoangaziwa",
    viewProcess: "Angalia Mchakato",
    contactUs: "Wasiliana Nasi",
    quickLinks: "Viungo vya Haraka",
    getInTouch: "Wasiliana Nasi",
    getInTouchDesc: "Una mradi? Wasiliana nasi. Hakuna wajibu.",
    testimonials: "Maoni ya Wateja",
    whatClientsSay: "Wateja Wetu Wanasema Nini",
    allRightsReserved: "Haki zote zimehifadhiwa.",
    landscapePlanning: "Upangaji & Usanifu wa Mandhari",
    landscapePlanningDesc: "Uchambuzi kamili wa eneo, upangaji mkuu, na usanifu wa bustani kwa suluhisho endelevu.",
    architecturalBuildings: "Majengo ya Usanifu & Ujenzi",
    architecturalBuildingsDesc: "Usanifu kamili wa majengo, ujenzi wa majengo, na huduma za uhandisi wa miundo.",
    projectManagement: "Usimamizi wa Miradi & Ujenzi",
    projectManagementDesc: "Usimamizi wa ujenzi kutoka mwanzo hadi mwisho kuhakikisha ubora.",
    close: "Funga",
    categories: "Aina",
    professionalExperienceDesc: "Timu yetu ina uzoefu wa zaidi ya miaka kumi katika usanifu wa mandhari, ubunifu wa majengo, na usimamizi wa miradi kote Tanzania na Afrika Mashariki.",
  },
  hi: {
    home: "होम",
    about: "हमारे बारे में",
    services: "सेवाएं",
    projects: "परियोजनाएं",
    contact: "संपर्क",
    professionalExperience: "पेशेवर अनुभव",
    tagline: "परिदृश्य बनाना, भविष्य को आकार देना",
    subtitle: "GreenScape Consults Tz Ltd",
    ourServices: "हमारी सेवाएं",
    viewProjects: "परियोजनाएं देखें",
    projectsCompleted: "परियोजनाएं",
    yearsExperience: "वर्ष",
    happyClients: "ग्राहक",
    aboutUs: "हमारे बारे में",
    whereArchMeetsNature: "जहाँ वास्तुकला प्रकृति से मिलती है",
    aboutDesc1: "तंजानिया में स्थापित, Greenscape Consults Tz एक गतिशील फर्म है।",
    aboutDesc2: "हमारा दृष्टिकोण सुनिश्चित करता है कि हर परियोजना एकीकृत दृष्टि के साथ डिज़ाइन की गई है।",
    ourVision: "हमारा विजन",
    visionDesc: "तंजानिया की अग्रणी एकीकृत डिजाइन भागीदार बनना।",
    ourMission: "हमारा मिशन",
    missionDesc: "हम भवनों और परिदृश्यों के लिए असाधारण समाधान प्रदान करते हैं।",
    whatWeDo: "हम क्या करते हैं",
    ourServicesTitle: "हमारी सेवाएं",
    viewCategories: "श्रेणियां देखें",
    portfolio: "पोर्टफोलियो",
    featuredProjects: "विशेष परियोजनाएं",
    viewProcess: "प्रक्रिया देखें",
    contactUs: "संपर्क करें",
    quickLinks: "त्वरित लिंक",
    getInTouch: "संपर्क करें",
    getInTouchDesc: "क्या आपकी कोई परियोजना है? संपर्क करें।",
    testimonials: "प्रशंसापत्र",
    whatClientsSay: "हमारे ग्राहक क्या कहते हैं",
    allRightsReserved: "सर्वाधिकार सुरक्षित।",
    landscapePlanning: "लैंडस्केप योजना और डिज़ाइन",
    landscapePlanningDesc: "व्यापक साइट विश्लेषण और मास्टर प्लानिंग।",
    architecturalBuildings: "वास्तुशिल्प भवन और निर्माण",
    architecturalBuildingsDesc: "पूर्ण वास्तुशिल्प डिजाइन और निर्माण सेवाएं।",
    projectManagement: "परियोजना प्रबंधन और निर्माण",
    projectManagementDesc: "गुणवत्ता सुनिश्चित करने के लिए निर्माण पर्यवेक्षण।",
    close: "बंद करें",
    categories: "श्रेणियां",
    professionalExperienceDesc: "हमारी टीम के पास तंजानिया और पूर्वी अफ्रीका में एक दशक से अधिक का अनुभव है।",
  },
  tr: {
    home: "Ana Sayfa",
    about: "Hakkında",
    services: "Hizmetler",
    projects: "Projeler",
    contact: "İletişim",
    professionalExperience: "Profesyonel Deneyim",
    tagline: "Peyzajlar İnşa Etmek, Gelecekleri Şekillendirmek",
    subtitle: "GreenScape Consults Tz Ltd",
    ourServices: "HİZMETLERİMİZ",
    viewProjects: "PROJELERİ GÖRÜNTÜLE",
    projectsCompleted: "Projeler",
    yearsExperience: "Yıl",
    happyClients: "Müşteriler",
    aboutUs: "Hakkımızda",
    whereArchMeetsNature: "Mimarinin Doğayla Buluştuğu Yer",
    aboutDesc1: "Tanzanya'da kurulan Greenscape Consults Tz, dinamik ve entegre bir firmadır.",
    aboutDesc2: "Yaklaşımımız her projenin birleşik bir vizyonla tasarlanmasını sağlar.",
    ourVision: "Vizyonumuz",
    visionDesc: "Tanzanya'nın lider entegre tasarım ortağı olmak.",
    ourMission: "Misyonumuz",
    missionDesc: "Binalar ve peyzajlar için olağanüstü çözümler sunuyoruz.",
    whatWeDo: "Ne Yapıyoruz",
    ourServicesTitle: "Hizmetlerimiz",
    viewCategories: "Kategorileri Görüntüle",
    portfolio: "Portföy",
    featuredProjects: "Öne Çıkan Projeler",
    viewProcess: "Süreci Görüntüle",
    contactUs: "Bize Ulaşın",
    quickLinks: "Hızlı Bağlantılar",
    getInTouch: "İletişime Geçin",
    getInTouchDesc: "Projeniz mi var? İletişime geçin.",
    testimonials: "Referanslar",
    whatClientsSay: "Müşterilerimiz Ne Diyor",
    allRightsReserved: "Tüm hakları saklıdır.",
    landscapePlanning: "Peyzaj Planlama ve Tasarım",
    landscapePlanningDesc: "Kapsamlı site analizi ve master planlama.",
    architecturalBuildings: "Mimari Binalar ve İnşaat",
    architecturalBuildingsDesc: "Tam mimari tasarım ve inşaat hizmetleri.",
    projectManagement: "Proje Yönetimi ve İnşaat",
    projectManagementDesc: "Kaliteyi sağlamak için inşaat denetimi.",
    close: "Kapat",
    categories: "Kategoriler",
    professionalExperienceDesc: "Ekibimiz Tanzanya ve Doğu Afrika'da on yılı aşkın deneyime sahiptir.",
  },
  zh: {
    home: "首页",
    about: "关于",
    services: "服务",
    projects: "项目",
    contact: "联系",
    professionalExperience: "专业经验",
    tagline: "建造景观，塑造未来",
    subtitle: "GreenScape Consults Tz Ltd",
    ourServices: "我们的服务",
    viewProjects: "查看项目",
    projectsCompleted: "项目",
    yearsExperience: "年",
    happyClients: "客户",
    aboutUs: "关于我们",
    whereArchMeetsNature: "建筑与自然相遇的地方",
    aboutDesc1: "Greenscape Consults Tz成立于坦桑尼亚，是一家充满活力的综合性公司。",
    aboutDesc2: "我们的方法确保每个项目都以统一的愿景进行设计。",
    ourVision: "我们的愿景",
    visionDesc: "成为坦桑尼亚领先的综合设计合作伙伴。",
    ourMission: "我们的使命",
    missionDesc: "我们为建筑和景观提供卓越的解决方案。",
    whatWeDo: "我们做什么",
    ourServicesTitle: "我们的服务",
    viewCategories: "查看类别",
    portfolio: "作品集",
    featuredProjects: "精选项目",
    viewProcess: "查看过程",
    contactUs: "联系我们",
    quickLinks: "快速链接",
    getInTouch: "联系我们",
    getInTouchDesc: "有项目吗？联系我们。",
    testimonials: "客户评价",
    whatClientsSay: "客户评价",
    allRightsReserved: "版权所有。",
    landscapePlanning: "景观规划与设计",
    landscapePlanningDesc: "全面的场地分析和总体规划。",
    architecturalBuildings: "建筑设计与施工",
    architecturalBuildingsDesc: "完整的建筑设计和施工服务。",
    projectManagement: "项目管理与施工",
    projectManagementDesc: "确保质量的施工监督。",
    close: "关闭",
    categories: "类别",
    professionalExperienceDesc: "我们的团队在坦桑尼亚和东非拥有超过十年的实践经验。",
  },
};

const languageNames: Record<Language, string> = {
  en: "English",
  sw: "Kiswahili",
  hi: "हिन्दी",
  tr: "Türkçe",
  zh: "中文",
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languageNames: Record<Language, string>;
  languages: Language[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string) => translations[language]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languageNames, languages: ["en", "sw", "hi", "tr", "zh"] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
